package com.lottchina.cplib.common

object Command {


    val CMD_STATION_CONNET = "SKT_S01"//校验Toen
    val CMD_STATION_CONNECT_ACTIVE = "SKT_BT01"
    val CMD_STATION_BIND_TERMINAL = "SKT_T01"
    val CMD_STATION_UNBIND_TERMINAL = "SKT_T02"
    val CMD_STATION_TICKET_GRAB_GET = "SKT_TK01"
    val CMD_STATION_TICKET_FINISH = "SKT_TK02"
    val CMD_STATION_BONUS_GET = "SKT_TK03"
    val CMD_STATION_BONUS_DETAIL_GET = "SKT_TK04"
    val CMD_STATION_BONUS_FINISH = "SKT_TK05"
    val CMD_STATION_TICKET_RECOVERY = "SKT_TK06"
    val CMD_STATION_BONUS_TICKET_FINISH = "SKT_TK07"

    val CMD_STATION_REGIST = "S01"
    val CMD_STATION_LOGIN = "S02"
    val CMD_STATION_GET_VERIFYCODE = "U01"
    val CMD_STATION_VERIFYCODE_LOGIN = "U02"
    val CMD_STATION_INFO_UPDATE = "S03"
    val CMD_STATION_GET_DETAIL = "S04"

    val CMD_STATION_ADD_TERMINAL = "ST01"
    val CMD_STATION_EDIT_TERMINAL = "ST02"
    val CMD_STATION_BOX_VERSION_UPDATE = "ST03"
    val CMD_STATION_MESSAGE = "SKTB_M01"
    val CMD_STATION_DATA = "SKT_RP01"
    val CMD_STATION_GET_ACCOUNT_DETAIL_LIST = "SA01"
    val CMD_STATION_CASH_MONEY = "SA02"

    val CMD_STATION_ADD_SPREAD_CHANNEL = "SC01"
    val CMD_STATION_GET_OFFLINE_BONUS_LIST = "STI08"
    val CMD_STATION_GET_TICKET_DATA = "STI06"
    val CMD_STATION_GET_MEMBER_LIST = "SCUS01"
    val CMD_STATION_MEMBER_CHARGE = "SCUS02"
    val CMD_STATION_MEMBER_NAME = "SCUS06"
    val CMD_STATION_TICKET_GET = "SKT_TK11"
    val CMD_STATION_OFFLINE_TICKET_GET = "SKT_TK08"
    val CMD_STATION_EXCEPTION_TICKET_GET = "STI01"
    val CMD_STATION_EXCEPTION_TICKET_TRYAGAIN = "STI03"
    val CMD_STATION_EXCEPTION_TICKET_REFUND = "STI04"
    val CMD_STATION_TICKET_DATA_GET = "SKT_RP02"
    val CMD_STATION_OFFLINE_TICKET_DATA_CONFIRM = "STI09"
    val CMD_STATION_GET_MEMBER_TICKET_DETAIL_LIST = "STI10"

    val CMD_STATION_TICKET_PRINT_GET = "SKT_TP01"
    val CMD_STATION_TICKET_PRINT_FINISH = "SKT_TP02"
    val CMD_STATION_TAKE_PRINT_FINISH = "SKT_TP03"
    val CMD_STATION_MEMBER_CASH_GET = "SCUS03"
    val CMD_STATION_MEMBER_CASH_SUCCESS = "SCUS04"

    val CMD_STATION_GET_MEMBER_ACCOUNT_DETAIL_LIST = "SCUSA01"


    val CMD_STATION_CHANEL_REMARK_SET = "SC02"
    val CMD_STATION_CHANEL_MEMBER_DATA = "SC03"

    val CMD_STATION_GET_MEMBER_DATA = "SCUS05"

    val CMD_STATION_SEND_MSG = "SKT_MSG01"

    val CMD_STATION_SCAN_ODDE = "STI05"

    val CMD_APP_CHECK_VERSION = "APP01"

    val CMD_STATION_GET_MEMBER_STAT = "SR01"

    val CMD_STATION_SCHEME_UPLOAD = "JST101"
    val CMD_STATION_SCHEME_GET_LIST = "JST102"
    val CMD_STATION_SCHEME_GET_DETAIL = "JST103"
    val CMD_STATION_GET_MEMBER_SCHEME_DETAIL_LIST = "JST013"
    val CMD_STATION_GET_SCHEME_TICKET_DETAIL_LIST = "CUST02"
    val CMD_STATION_SCHEME_GET_JOINT_LIST = "JST301"
    val CMD_APP_CHECK_SYSTIME = "SYS01"

    val CMD_STATION_TICKET_PRINT_STOP_NOTIFY = "JST038"

    val CMD_STATION_UPLOAD_REPORT = "SKT_TR01"
    val CMD_STATION_UPLOAD_OPEN_NUMBER = "SKT_TM01"

    val CMD_DELETE_CHANNEL = "JST043"
    val CMD_UPDATE_CHANNEL = "JST044"


    val CMD_GETTERM_BY_TERMID = "TM05"

    val CMD_STATION_TICKET_PIC_UPLOAD = "STI11"

    val CMD_STATION_GET_QRCODE = "JST501"
    //订单出票之 获取方案列表Scheme list
    val CMD_STATION_TICKET_SCHEME_LIST = "SKT_TK12"

    //下一步
    val CMD_NEXT_STEP = "US02"
    //终端登录接口
    val CMD_TERMINAL_LOGIN = "ST04"
    //查看当前终端锁定票信息。
    val CMD_LOCKED_TICKETS = "SKT_RP03"
    //获取待上传照片票的列表。
    val CMD_PHOTO_TICKETS = "SKT_TK14"
    //获取待上传照片票的列表。
    val CMD_PHOTO_UPLOAD = "SKT_TK15"
    //获取收款接单的列表
    val CMD_RECEIPT_ORDER = "SSCH01"
    //获取账户余额
    val CMD_ACCOUNT_BALANCE = "JCT06"
    // 结算 Settlement
    val CMD_SETTLEMENT = "JST030"
    // 删除无效方案
    val CMD_DELETE_PROGRAM = "JST040"
    // 获取整个方案的票方案
    val CMD_LOAD_ALL_PROGRAM = "SKT_TK10"


}

